### ISSUE TITLE
"Apply tag filter" doesn't affect anything

### ISSUE THREAD

**Issue by MarvyD** [HaW-Tagger/HWtagger#4]
I have "Apply tag filter" unchecked, but i still have a field with some tags rejected after creation of a dataset, with no way to quickly add all of them back for all images.  
![Screenshot 2024-10-31 184449](https://github.com/user-attachments/assets/a226b905-461f-4947-94c4-6f12bbc6f2f0)

My version of Python is 3.10.11. I didn't install CUDA, because WD Tagger appears to run on GPU even without it.

Also is it possible for user to add other WD models like "WD EVA02-Large Tagger v3" ?

**Comment by PhoenixAscencio** [comment]
I added a checkbox to deactivate the filter if you don't want it in the settings, (and removed the checkbox for filters in the database creation tab), (you can deactivate the filter in the settings then load a database then apply filter and it will remove the filter for all images).
I'm thinking of adding the large Tagger since it has some interesting properties to explore in its tagging capabilities.

**Comment by PhoenixAscencio** [comment]
Also, we don't have a simple way that we could add user specific models but we have ways to expand the available model list easily (something like 10 minutes to add it properly) as long as it's a common architecture. I also added wd-eva02-large-tagger-v3 to the tagger so you can use it right now.
