### ISSUE TITLE
Swinv2v3 produces noticeably worse results with this application

### ISSUE THREAD

**Issue by MarvyD** [HaW-Tagger/HWtagger#5]
Example:
Image:
![TEST](https://github.com/user-attachments/assets/15709c65-fcad-4c4a-9fd8-ce2536a1329e)

Outputs using [ComfyUI WD 1.4 Tagger ](https://github.com/pythongosssss/ComfyUI-WD14-Tagger)
![Screenshot1](https://github.com/user-attachments/assets/23f7923e-0d36-4eeb-95ac-4ab2d1e37ab0)

Outputs using HWtagger
![Screenshot2](https://github.com/user-attachments/assets/6ef32dfc-a4a0-48f8-945e-569443fdf120)

Settings
![image(2)](https://github.com/user-attachments/assets/183f7b05-9c17-4a98-860e-f5e4c3a36a07)

**Comment by PhoenixAscencio** [comment]
I'm currently checking it, wand will come back to you after I do some tests

**Comment by PhoenixAscencio** [comment]
Okay so thanks for the feedback. This is only the case for elongated images and the culprit is that for our processing of images we _resized_ them when we should've padded them with white. We did that at the time because it had the bad tendency of adding a bunch of letterboxed & similar tags. This correction was overblown though so maybe padding it would be the best move.

**Comment by PhoenixAscencio** [comment]
This is now fixed, it added letterboxed and messed up the tagging a bit because we mistakenly were padding the images black instead of white, but it is now resolved
